// Generated by gencpp from file stepper_motor/set_stepper_motorRequest.msg
// DO NOT EDIT!


#ifndef STEPPER_MOTOR_MESSAGE_SET_STEPPER_MOTORREQUEST_H
#define STEPPER_MOTOR_MESSAGE_SET_STEPPER_MOTORREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace stepper_motor
{
template <class ContainerAllocator>
struct set_stepper_motorRequest_
{
  typedef set_stepper_motorRequest_<ContainerAllocator> Type;

  set_stepper_motorRequest_()
    : velocity(0.0)  {
    }
  set_stepper_motorRequest_(const ContainerAllocator& _alloc)
    : velocity(0.0)  {
  (void)_alloc;
    }



   typedef float _velocity_type;
  _velocity_type velocity;





  typedef boost::shared_ptr< ::stepper_motor::set_stepper_motorRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::stepper_motor::set_stepper_motorRequest_<ContainerAllocator> const> ConstPtr;

}; // struct set_stepper_motorRequest_

typedef ::stepper_motor::set_stepper_motorRequest_<std::allocator<void> > set_stepper_motorRequest;

typedef boost::shared_ptr< ::stepper_motor::set_stepper_motorRequest > set_stepper_motorRequestPtr;
typedef boost::shared_ptr< ::stepper_motor::set_stepper_motorRequest const> set_stepper_motorRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::stepper_motor::set_stepper_motorRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::stepper_motor::set_stepper_motorRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::stepper_motor::set_stepper_motorRequest_<ContainerAllocator1> & lhs, const ::stepper_motor::set_stepper_motorRequest_<ContainerAllocator2> & rhs)
{
  return lhs.velocity == rhs.velocity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::stepper_motor::set_stepper_motorRequest_<ContainerAllocator1> & lhs, const ::stepper_motor::set_stepper_motorRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace stepper_motor

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::stepper_motor::set_stepper_motorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stepper_motor::set_stepper_motorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stepper_motor::set_stepper_motorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stepper_motor::set_stepper_motorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stepper_motor::set_stepper_motorRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stepper_motor::set_stepper_motorRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::stepper_motor::set_stepper_motorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e4ff88b32504f688719a85e0753f63ce";
  }

  static const char* value(const ::stepper_motor::set_stepper_motorRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe4ff88b32504f688ULL;
  static const uint64_t static_value2 = 0x719a85e0753f63ceULL;
};

template<class ContainerAllocator>
struct DataType< ::stepper_motor::set_stepper_motorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "stepper_motor/set_stepper_motorRequest";
  }

  static const char* value(const ::stepper_motor::set_stepper_motorRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::stepper_motor::set_stepper_motorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 velocity\n"
;
  }

  static const char* value(const ::stepper_motor::set_stepper_motorRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::stepper_motor::set_stepper_motorRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct set_stepper_motorRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::stepper_motor::set_stepper_motorRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::stepper_motor::set_stepper_motorRequest_<ContainerAllocator>& v)
  {
    s << indent << "velocity: ";
    Printer<float>::stream(s, indent + "  ", v.velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STEPPER_MOTOR_MESSAGE_SET_STEPPER_MOTORREQUEST_H
