// Generated by gencpp from file stepper_motor/set_stepper_motor.msg
// DO NOT EDIT!


#ifndef STEPPER_MOTOR_MESSAGE_SET_STEPPER_MOTOR_H
#define STEPPER_MOTOR_MESSAGE_SET_STEPPER_MOTOR_H

#include <ros/service_traits.h>


#include <stepper_motor/set_stepper_motorRequest.h>
#include <stepper_motor/set_stepper_motorResponse.h>


namespace stepper_motor
{

struct set_stepper_motor
{

typedef set_stepper_motorRequest Request;
typedef set_stepper_motorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_stepper_motor
} // namespace stepper_motor


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::stepper_motor::set_stepper_motor > {
  static const char* value()
  {
    return "e4ff88b32504f688719a85e0753f63ce";
  }

  static const char* value(const ::stepper_motor::set_stepper_motor&) { return value(); }
};

template<>
struct DataType< ::stepper_motor::set_stepper_motor > {
  static const char* value()
  {
    return "stepper_motor/set_stepper_motor";
  }

  static const char* value(const ::stepper_motor::set_stepper_motor&) { return value(); }
};


// service_traits::MD5Sum< ::stepper_motor::set_stepper_motorRequest> should match
// service_traits::MD5Sum< ::stepper_motor::set_stepper_motor >
template<>
struct MD5Sum< ::stepper_motor::set_stepper_motorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::stepper_motor::set_stepper_motor >::value();
  }
  static const char* value(const ::stepper_motor::set_stepper_motorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::stepper_motor::set_stepper_motorRequest> should match
// service_traits::DataType< ::stepper_motor::set_stepper_motor >
template<>
struct DataType< ::stepper_motor::set_stepper_motorRequest>
{
  static const char* value()
  {
    return DataType< ::stepper_motor::set_stepper_motor >::value();
  }
  static const char* value(const ::stepper_motor::set_stepper_motorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::stepper_motor::set_stepper_motorResponse> should match
// service_traits::MD5Sum< ::stepper_motor::set_stepper_motor >
template<>
struct MD5Sum< ::stepper_motor::set_stepper_motorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::stepper_motor::set_stepper_motor >::value();
  }
  static const char* value(const ::stepper_motor::set_stepper_motorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::stepper_motor::set_stepper_motorResponse> should match
// service_traits::DataType< ::stepper_motor::set_stepper_motor >
template<>
struct DataType< ::stepper_motor::set_stepper_motorResponse>
{
  static const char* value()
  {
    return DataType< ::stepper_motor::set_stepper_motor >::value();
  }
  static const char* value(const ::stepper_motor::set_stepper_motorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STEPPER_MOTOR_MESSAGE_SET_STEPPER_MOTOR_H
