// Generated by gencpp from file stepper_motor/set_stepper_motorResponse.msg
// DO NOT EDIT!


#ifndef STEPPER_MOTOR_MESSAGE_SET_STEPPER_MOTORRESPONSE_H
#define STEPPER_MOTOR_MESSAGE_SET_STEPPER_MOTORRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace stepper_motor
{
template <class ContainerAllocator>
struct set_stepper_motorResponse_
{
  typedef set_stepper_motorResponse_<ContainerAllocator> Type;

  set_stepper_motorResponse_()
    {
    }
  set_stepper_motorResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::stepper_motor::set_stepper_motorResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::stepper_motor::set_stepper_motorResponse_<ContainerAllocator> const> ConstPtr;

}; // struct set_stepper_motorResponse_

typedef ::stepper_motor::set_stepper_motorResponse_<std::allocator<void> > set_stepper_motorResponse;

typedef boost::shared_ptr< ::stepper_motor::set_stepper_motorResponse > set_stepper_motorResponsePtr;
typedef boost::shared_ptr< ::stepper_motor::set_stepper_motorResponse const> set_stepper_motorResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::stepper_motor::set_stepper_motorResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::stepper_motor::set_stepper_motorResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace stepper_motor

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::stepper_motor::set_stepper_motorResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stepper_motor::set_stepper_motorResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stepper_motor::set_stepper_motorResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stepper_motor::set_stepper_motorResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stepper_motor::set_stepper_motorResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stepper_motor::set_stepper_motorResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::stepper_motor::set_stepper_motorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::stepper_motor::set_stepper_motorResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::stepper_motor::set_stepper_motorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "stepper_motor/set_stepper_motorResponse";
  }

  static const char* value(const ::stepper_motor::set_stepper_motorResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::stepper_motor::set_stepper_motorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::stepper_motor::set_stepper_motorResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::stepper_motor::set_stepper_motorResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct set_stepper_motorResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::stepper_motor::set_stepper_motorResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::stepper_motor::set_stepper_motorResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // STEPPER_MOTOR_MESSAGE_SET_STEPPER_MOTORRESPONSE_H
