// Generated by gencpp from file asdr/get_state.msg
// DO NOT EDIT!


#ifndef ASDR_MESSAGE_GET_STATE_H
#define ASDR_MESSAGE_GET_STATE_H

#include <ros/service_traits.h>


#include <asdr/get_stateRequest.h>
#include <asdr/get_stateResponse.h>


namespace asdr
{

struct get_state
{

typedef get_stateRequest Request;
typedef get_stateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct get_state
} // namespace asdr


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::asdr::get_state > {
  static const char* value()
  {
    return "af6d3a99f0fbeb66d3248fa4b3e675fb";
  }

  static const char* value(const ::asdr::get_state&) { return value(); }
};

template<>
struct DataType< ::asdr::get_state > {
  static const char* value()
  {
    return "asdr/get_state";
  }

  static const char* value(const ::asdr::get_state&) { return value(); }
};


// service_traits::MD5Sum< ::asdr::get_stateRequest> should match
// service_traits::MD5Sum< ::asdr::get_state >
template<>
struct MD5Sum< ::asdr::get_stateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::asdr::get_state >::value();
  }
  static const char* value(const ::asdr::get_stateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::asdr::get_stateRequest> should match
// service_traits::DataType< ::asdr::get_state >
template<>
struct DataType< ::asdr::get_stateRequest>
{
  static const char* value()
  {
    return DataType< ::asdr::get_state >::value();
  }
  static const char* value(const ::asdr::get_stateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::asdr::get_stateResponse> should match
// service_traits::MD5Sum< ::asdr::get_state >
template<>
struct MD5Sum< ::asdr::get_stateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::asdr::get_state >::value();
  }
  static const char* value(const ::asdr::get_stateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::asdr::get_stateResponse> should match
// service_traits::DataType< ::asdr::get_state >
template<>
struct DataType< ::asdr::get_stateResponse>
{
  static const char* value()
  {
    return DataType< ::asdr::get_state >::value();
  }
  static const char* value(const ::asdr::get_stateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASDR_MESSAGE_GET_STATE_H
