// Generated by gencpp from file asdr/set_stateRequest.msg
// DO NOT EDIT!


#ifndef ASDR_MESSAGE_SET_STATEREQUEST_H
#define ASDR_MESSAGE_SET_STATEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace asdr
{
template <class ContainerAllocator>
struct set_stateRequest_
{
  typedef set_stateRequest_<ContainerAllocator> Type;

  set_stateRequest_()
    : state()  {
    }
  set_stateRequest_(const ContainerAllocator& _alloc)
    : state(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::asdr::set_stateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::asdr::set_stateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct set_stateRequest_

typedef ::asdr::set_stateRequest_<std::allocator<void> > set_stateRequest;

typedef boost::shared_ptr< ::asdr::set_stateRequest > set_stateRequestPtr;
typedef boost::shared_ptr< ::asdr::set_stateRequest const> set_stateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::asdr::set_stateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::asdr::set_stateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::asdr::set_stateRequest_<ContainerAllocator1> & lhs, const ::asdr::set_stateRequest_<ContainerAllocator2> & rhs)
{
  return lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::asdr::set_stateRequest_<ContainerAllocator1> & lhs, const ::asdr::set_stateRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace asdr

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::asdr::set_stateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::asdr::set_stateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::asdr::set_stateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::asdr::set_stateRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::asdr::set_stateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::asdr::set_stateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::asdr::set_stateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "af6d3a99f0fbeb66d3248fa4b3e675fb";
  }

  static const char* value(const ::asdr::set_stateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaf6d3a99f0fbeb66ULL;
  static const uint64_t static_value2 = 0xd3248fa4b3e675fbULL;
};

template<class ContainerAllocator>
struct DataType< ::asdr::set_stateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "asdr/set_stateRequest";
  }

  static const char* value(const ::asdr::set_stateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::asdr::set_stateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string state\n"
;
  }

  static const char* value(const ::asdr::set_stateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::asdr::set_stateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct set_stateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::asdr::set_stateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::asdr::set_stateRequest_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASDR_MESSAGE_SET_STATEREQUEST_H
