// Generated by gencpp from file asdr/set_state.msg
// DO NOT EDIT!


#ifndef ASDR_MESSAGE_SET_STATE_H
#define ASDR_MESSAGE_SET_STATE_H

#include <ros/service_traits.h>


#include <asdr/set_stateRequest.h>
#include <asdr/set_stateResponse.h>


namespace asdr
{

struct set_state
{

typedef set_stateRequest Request;
typedef set_stateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_state
} // namespace asdr


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::asdr::set_state > {
  static const char* value()
  {
    return "af6d3a99f0fbeb66d3248fa4b3e675fb";
  }

  static const char* value(const ::asdr::set_state&) { return value(); }
};

template<>
struct DataType< ::asdr::set_state > {
  static const char* value()
  {
    return "asdr/set_state";
  }

  static const char* value(const ::asdr::set_state&) { return value(); }
};


// service_traits::MD5Sum< ::asdr::set_stateRequest> should match
// service_traits::MD5Sum< ::asdr::set_state >
template<>
struct MD5Sum< ::asdr::set_stateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::asdr::set_state >::value();
  }
  static const char* value(const ::asdr::set_stateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::asdr::set_stateRequest> should match
// service_traits::DataType< ::asdr::set_state >
template<>
struct DataType< ::asdr::set_stateRequest>
{
  static const char* value()
  {
    return DataType< ::asdr::set_state >::value();
  }
  static const char* value(const ::asdr::set_stateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::asdr::set_stateResponse> should match
// service_traits::MD5Sum< ::asdr::set_state >
template<>
struct MD5Sum< ::asdr::set_stateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::asdr::set_state >::value();
  }
  static const char* value(const ::asdr::set_stateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::asdr::set_stateResponse> should match
// service_traits::DataType< ::asdr::set_state >
template<>
struct DataType< ::asdr::set_stateResponse>
{
  static const char* value()
  {
    return DataType< ::asdr::set_state >::value();
  }
  static const char* value(const ::asdr::set_stateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASDR_MESSAGE_SET_STATE_H
