// Generated by gencpp from file asdr/set_velocityRequest.msg
// DO NOT EDIT!


#ifndef ASDR_MESSAGE_SET_VELOCITYREQUEST_H
#define ASDR_MESSAGE_SET_VELOCITYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace asdr
{
template <class ContainerAllocator>
struct set_velocityRequest_
{
  typedef set_velocityRequest_<ContainerAllocator> Type;

  set_velocityRequest_()
    : linear(0.0)
    , angular(0.0)  {
    }
  set_velocityRequest_(const ContainerAllocator& _alloc)
    : linear(0.0)
    , angular(0.0)  {
  (void)_alloc;
    }



   typedef double _linear_type;
  _linear_type linear;

   typedef double _angular_type;
  _angular_type angular;





  typedef boost::shared_ptr< ::asdr::set_velocityRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::asdr::set_velocityRequest_<ContainerAllocator> const> ConstPtr;

}; // struct set_velocityRequest_

typedef ::asdr::set_velocityRequest_<std::allocator<void> > set_velocityRequest;

typedef boost::shared_ptr< ::asdr::set_velocityRequest > set_velocityRequestPtr;
typedef boost::shared_ptr< ::asdr::set_velocityRequest const> set_velocityRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::asdr::set_velocityRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::asdr::set_velocityRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::asdr::set_velocityRequest_<ContainerAllocator1> & lhs, const ::asdr::set_velocityRequest_<ContainerAllocator2> & rhs)
{
  return lhs.linear == rhs.linear &&
    lhs.angular == rhs.angular;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::asdr::set_velocityRequest_<ContainerAllocator1> & lhs, const ::asdr::set_velocityRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace asdr

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::asdr::set_velocityRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::asdr::set_velocityRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::asdr::set_velocityRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::asdr::set_velocityRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::asdr::set_velocityRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::asdr::set_velocityRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::asdr::set_velocityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "144a16e4d6b53a0dbadc2e617460a173";
  }

  static const char* value(const ::asdr::set_velocityRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x144a16e4d6b53a0dULL;
  static const uint64_t static_value2 = 0xbadc2e617460a173ULL;
};

template<class ContainerAllocator>
struct DataType< ::asdr::set_velocityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "asdr/set_velocityRequest";
  }

  static const char* value(const ::asdr::set_velocityRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::asdr::set_velocityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 linear\n"
"float64 angular\n"
;
  }

  static const char* value(const ::asdr::set_velocityRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::asdr::set_velocityRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.linear);
      stream.next(m.angular);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct set_velocityRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::asdr::set_velocityRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::asdr::set_velocityRequest_<ContainerAllocator>& v)
  {
    s << indent << "linear: ";
    Printer<double>::stream(s, indent + "  ", v.linear);
    s << indent << "angular: ";
    Printer<double>::stream(s, indent + "  ", v.angular);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASDR_MESSAGE_SET_VELOCITYREQUEST_H
