// Generated by gencpp from file asdr/set_velocityResponse.msg
// DO NOT EDIT!


#ifndef ASDR_MESSAGE_SET_VELOCITYRESPONSE_H
#define ASDR_MESSAGE_SET_VELOCITYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace asdr
{
template <class ContainerAllocator>
struct set_velocityResponse_
{
  typedef set_velocityResponse_<ContainerAllocator> Type;

  set_velocityResponse_()
    {
    }
  set_velocityResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::asdr::set_velocityResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::asdr::set_velocityResponse_<ContainerAllocator> const> ConstPtr;

}; // struct set_velocityResponse_

typedef ::asdr::set_velocityResponse_<std::allocator<void> > set_velocityResponse;

typedef boost::shared_ptr< ::asdr::set_velocityResponse > set_velocityResponsePtr;
typedef boost::shared_ptr< ::asdr::set_velocityResponse const> set_velocityResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::asdr::set_velocityResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::asdr::set_velocityResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace asdr

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::asdr::set_velocityResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::asdr::set_velocityResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::asdr::set_velocityResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::asdr::set_velocityResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::asdr::set_velocityResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::asdr::set_velocityResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::asdr::set_velocityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::asdr::set_velocityResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::asdr::set_velocityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "asdr/set_velocityResponse";
  }

  static const char* value(const ::asdr::set_velocityResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::asdr::set_velocityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::asdr::set_velocityResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::asdr::set_velocityResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct set_velocityResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::asdr::set_velocityResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::asdr::set_velocityResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ASDR_MESSAGE_SET_VELOCITYRESPONSE_H
