// Generated by gencpp from file rotary_encoder/get_rotary_encoderRequest.msg
// DO NOT EDIT!


#ifndef ROTARY_ENCODER_MESSAGE_GET_ROTARY_ENCODERREQUEST_H
#define ROTARY_ENCODER_MESSAGE_GET_ROTARY_ENCODERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rotary_encoder
{
template <class ContainerAllocator>
struct get_rotary_encoderRequest_
{
  typedef get_rotary_encoderRequest_<ContainerAllocator> Type;

  get_rotary_encoderRequest_()
    {
    }
  get_rotary_encoderRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::rotary_encoder::get_rotary_encoderRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rotary_encoder::get_rotary_encoderRequest_<ContainerAllocator> const> ConstPtr;

}; // struct get_rotary_encoderRequest_

typedef ::rotary_encoder::get_rotary_encoderRequest_<std::allocator<void> > get_rotary_encoderRequest;

typedef boost::shared_ptr< ::rotary_encoder::get_rotary_encoderRequest > get_rotary_encoderRequestPtr;
typedef boost::shared_ptr< ::rotary_encoder::get_rotary_encoderRequest const> get_rotary_encoderRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rotary_encoder::get_rotary_encoderRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rotary_encoder::get_rotary_encoderRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace rotary_encoder

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rotary_encoder::get_rotary_encoderRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rotary_encoder::get_rotary_encoderRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rotary_encoder::get_rotary_encoderRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rotary_encoder::get_rotary_encoderRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rotary_encoder::get_rotary_encoderRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rotary_encoder::get_rotary_encoderRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rotary_encoder::get_rotary_encoderRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::rotary_encoder::get_rotary_encoderRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::rotary_encoder::get_rotary_encoderRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rotary_encoder/get_rotary_encoderRequest";
  }

  static const char* value(const ::rotary_encoder::get_rotary_encoderRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rotary_encoder::get_rotary_encoderRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::rotary_encoder::get_rotary_encoderRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rotary_encoder::get_rotary_encoderRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct get_rotary_encoderRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rotary_encoder::get_rotary_encoderRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::rotary_encoder::get_rotary_encoderRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ROTARY_ENCODER_MESSAGE_GET_ROTARY_ENCODERREQUEST_H
