// Generated by gencpp from file rotary_encoder/get_rotary_encoderResponse.msg
// DO NOT EDIT!


#ifndef ROTARY_ENCODER_MESSAGE_GET_ROTARY_ENCODERRESPONSE_H
#define ROTARY_ENCODER_MESSAGE_GET_ROTARY_ENCODERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rotary_encoder
{
template <class ContainerAllocator>
struct get_rotary_encoderResponse_
{
  typedef get_rotary_encoderResponse_<ContainerAllocator> Type;

  get_rotary_encoderResponse_()
    : position(0.0)
    , velocity(0.0)  {
    }
  get_rotary_encoderResponse_(const ContainerAllocator& _alloc)
    : position(0.0)
    , velocity(0.0)  {
  (void)_alloc;
    }



   typedef float _position_type;
  _position_type position;

   typedef float _velocity_type;
  _velocity_type velocity;





  typedef boost::shared_ptr< ::rotary_encoder::get_rotary_encoderResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rotary_encoder::get_rotary_encoderResponse_<ContainerAllocator> const> ConstPtr;

}; // struct get_rotary_encoderResponse_

typedef ::rotary_encoder::get_rotary_encoderResponse_<std::allocator<void> > get_rotary_encoderResponse;

typedef boost::shared_ptr< ::rotary_encoder::get_rotary_encoderResponse > get_rotary_encoderResponsePtr;
typedef boost::shared_ptr< ::rotary_encoder::get_rotary_encoderResponse const> get_rotary_encoderResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rotary_encoder::get_rotary_encoderResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rotary_encoder::get_rotary_encoderResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rotary_encoder::get_rotary_encoderResponse_<ContainerAllocator1> & lhs, const ::rotary_encoder::get_rotary_encoderResponse_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position &&
    lhs.velocity == rhs.velocity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rotary_encoder::get_rotary_encoderResponse_<ContainerAllocator1> & lhs, const ::rotary_encoder::get_rotary_encoderResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rotary_encoder

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rotary_encoder::get_rotary_encoderResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rotary_encoder::get_rotary_encoderResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rotary_encoder::get_rotary_encoderResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rotary_encoder::get_rotary_encoderResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rotary_encoder::get_rotary_encoderResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rotary_encoder::get_rotary_encoderResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rotary_encoder::get_rotary_encoderResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2cf6c2ef6d4814960f7bd2c448525593";
  }

  static const char* value(const ::rotary_encoder::get_rotary_encoderResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2cf6c2ef6d481496ULL;
  static const uint64_t static_value2 = 0x0f7bd2c448525593ULL;
};

template<class ContainerAllocator>
struct DataType< ::rotary_encoder::get_rotary_encoderResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rotary_encoder/get_rotary_encoderResponse";
  }

  static const char* value(const ::rotary_encoder::get_rotary_encoderResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rotary_encoder::get_rotary_encoderResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 position\n"
"float32 velocity\n"
;
  }

  static const char* value(const ::rotary_encoder::get_rotary_encoderResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rotary_encoder::get_rotary_encoderResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct get_rotary_encoderResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rotary_encoder::get_rotary_encoderResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rotary_encoder::get_rotary_encoderResponse_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    Printer<float>::stream(s, indent + "  ", v.position);
    s << indent << "velocity: ";
    Printer<float>::stream(s, indent + "  ", v.velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROTARY_ENCODER_MESSAGE_GET_ROTARY_ENCODERRESPONSE_H
