// Generated by gencpp from file coverage_path_planner/make_planRequest.msg
// DO NOT EDIT!


#ifndef COVERAGE_PATH_PLANNER_MESSAGE_MAKE_PLANREQUEST_H
#define COVERAGE_PATH_PLANNER_MESSAGE_MAKE_PLANREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace coverage_path_planner
{
template <class ContainerAllocator>
struct make_planRequest_
{
  typedef make_planRequest_<ContainerAllocator> Type;

  make_planRequest_()
    {
    }
  make_planRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::coverage_path_planner::make_planRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::coverage_path_planner::make_planRequest_<ContainerAllocator> const> ConstPtr;

}; // struct make_planRequest_

typedef ::coverage_path_planner::make_planRequest_<std::allocator<void> > make_planRequest;

typedef boost::shared_ptr< ::coverage_path_planner::make_planRequest > make_planRequestPtr;
typedef boost::shared_ptr< ::coverage_path_planner::make_planRequest const> make_planRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::coverage_path_planner::make_planRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::coverage_path_planner::make_planRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace coverage_path_planner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::coverage_path_planner::make_planRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::coverage_path_planner::make_planRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::coverage_path_planner::make_planRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::coverage_path_planner::make_planRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coverage_path_planner::make_planRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coverage_path_planner::make_planRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::coverage_path_planner::make_planRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::coverage_path_planner::make_planRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::coverage_path_planner::make_planRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "coverage_path_planner/make_planRequest";
  }

  static const char* value(const ::coverage_path_planner::make_planRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::coverage_path_planner::make_planRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::coverage_path_planner::make_planRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::coverage_path_planner::make_planRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct make_planRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::coverage_path_planner::make_planRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::coverage_path_planner::make_planRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // COVERAGE_PATH_PLANNER_MESSAGE_MAKE_PLANREQUEST_H
