(cl:defpackage asdr-srv
  (:use )
  (:export
   "GET_STATE"
   "<GET_STATE-REQUEST>"
   "GET_STATE-REQUEST"
   "<GET_STATE-RESPONSE>"
   "GET_STATE-RESPONSE"
   "SET_STATE"
   "<SET_STATE-REQUEST>"
   "SET_STATE-REQUEST"
   "<SET_STATE-RESPONSE>"
   "SET_STATE-RESPONSE"
   "SET_VELOCITY"
   "<SET_VELOCITY-REQUEST>"
   "SET_VELOCITY-REQUEST"
   "<SET_VELOCITY-RESPONSE>"
   "SET_VELOCITY-RESPONSE"
  ))

