// Generated by gencpp from file serial_command_client/send_command.msg
// DO NOT EDIT!


#ifndef SERIAL_COMMAND_CLIENT_MESSAGE_SEND_COMMAND_H
#define SERIAL_COMMAND_CLIENT_MESSAGE_SEND_COMMAND_H

#include <ros/service_traits.h>


#include <serial_command_client/send_commandRequest.h>
#include <serial_command_client/send_commandResponse.h>


namespace serial_command_client
{

struct send_command
{

typedef send_commandRequest Request;
typedef send_commandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct send_command
} // namespace serial_command_client


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::serial_command_client::send_command > {
  static const char* value()
  {
    return "6be57eb71fc2c8bb590b1bea40258ebc";
  }

  static const char* value(const ::serial_command_client::send_command&) { return value(); }
};

template<>
struct DataType< ::serial_command_client::send_command > {
  static const char* value()
  {
    return "serial_command_client/send_command";
  }

  static const char* value(const ::serial_command_client::send_command&) { return value(); }
};


// service_traits::MD5Sum< ::serial_command_client::send_commandRequest> should match
// service_traits::MD5Sum< ::serial_command_client::send_command >
template<>
struct MD5Sum< ::serial_command_client::send_commandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::serial_command_client::send_command >::value();
  }
  static const char* value(const ::serial_command_client::send_commandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::serial_command_client::send_commandRequest> should match
// service_traits::DataType< ::serial_command_client::send_command >
template<>
struct DataType< ::serial_command_client::send_commandRequest>
{
  static const char* value()
  {
    return DataType< ::serial_command_client::send_command >::value();
  }
  static const char* value(const ::serial_command_client::send_commandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::serial_command_client::send_commandResponse> should match
// service_traits::MD5Sum< ::serial_command_client::send_command >
template<>
struct MD5Sum< ::serial_command_client::send_commandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::serial_command_client::send_command >::value();
  }
  static const char* value(const ::serial_command_client::send_commandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::serial_command_client::send_commandResponse> should match
// service_traits::DataType< ::serial_command_client::send_command >
template<>
struct DataType< ::serial_command_client::send_commandResponse>
{
  static const char* value()
  {
    return DataType< ::serial_command_client::send_command >::value();
  }
  static const char* value(const ::serial_command_client::send_commandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERIAL_COMMAND_CLIENT_MESSAGE_SEND_COMMAND_H
