// Generated by gencpp from file discovery/discoverResponse.msg
// DO NOT EDIT!


#ifndef DISCOVERY_MESSAGE_DISCOVERRESPONSE_H
#define DISCOVERY_MESSAGE_DISCOVERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace discovery
{
template <class ContainerAllocator>
struct discoverResponse_
{
  typedef discoverResponse_<ContainerAllocator> Type;

  discoverResponse_()
    : status(0)
    , pose()  {
    }
  discoverResponse_(const ContainerAllocator& _alloc)
    : status(0)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(FAILURE)
  #undef FAILURE
#endif
#if defined(_WIN32) && defined(SUCCESS)
  #undef SUCCESS
#endif

  enum {
    FAILURE = 0u,
    SUCCESS = 1u,
  };


  typedef boost::shared_ptr< ::discovery::discoverResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::discovery::discoverResponse_<ContainerAllocator> const> ConstPtr;

}; // struct discoverResponse_

typedef ::discovery::discoverResponse_<std::allocator<void> > discoverResponse;

typedef boost::shared_ptr< ::discovery::discoverResponse > discoverResponsePtr;
typedef boost::shared_ptr< ::discovery::discoverResponse const> discoverResponseConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::discovery::discoverResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::discovery::discoverResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::discovery::discoverResponse_<ContainerAllocator1> & lhs, const ::discovery::discoverResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::discovery::discoverResponse_<ContainerAllocator1> & lhs, const ::discovery::discoverResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace discovery

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::discovery::discoverResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::discovery::discoverResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::discovery::discoverResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::discovery::discoverResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::discovery::discoverResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::discovery::discoverResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::discovery::discoverResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "92972308c7fadb3f91e8ad956494a137";
  }

  static const char* value(const ::discovery::discoverResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x92972308c7fadb3fULL;
  static const uint64_t static_value2 = 0x91e8ad956494a137ULL;
};

template<class ContainerAllocator>
struct DataType< ::discovery::discoverResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "discovery/discoverResponse";
  }

  static const char* value(const ::discovery::discoverResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::discovery::discoverResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 FAILURE=0\n"
"uint8 SUCCESS=1\n"
"uint8 status\n"
"geometry_msgs/Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::discovery::discoverResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::discovery::discoverResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct discoverResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::discovery::discoverResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::discovery::discoverResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DISCOVERY_MESSAGE_DISCOVERRESPONSE_H
