// Generated by gencpp from file uvc_light/set_uvc_light.msg
// DO NOT EDIT!


#ifndef UVC_LIGHT_MESSAGE_SET_UVC_LIGHT_H
#define UVC_LIGHT_MESSAGE_SET_UVC_LIGHT_H

#include <ros/service_traits.h>


#include <uvc_light/set_uvc_lightRequest.h>
#include <uvc_light/set_uvc_lightResponse.h>


namespace uvc_light
{

struct set_uvc_light
{

typedef set_uvc_lightRequest Request;
typedef set_uvc_lightResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_uvc_light
} // namespace uvc_light


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uvc_light::set_uvc_light > {
  static const char* value()
  {
    return "8f77c0161e0f2021493136bb5f3f0e51";
  }

  static const char* value(const ::uvc_light::set_uvc_light&) { return value(); }
};

template<>
struct DataType< ::uvc_light::set_uvc_light > {
  static const char* value()
  {
    return "uvc_light/set_uvc_light";
  }

  static const char* value(const ::uvc_light::set_uvc_light&) { return value(); }
};


// service_traits::MD5Sum< ::uvc_light::set_uvc_lightRequest> should match
// service_traits::MD5Sum< ::uvc_light::set_uvc_light >
template<>
struct MD5Sum< ::uvc_light::set_uvc_lightRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uvc_light::set_uvc_light >::value();
  }
  static const char* value(const ::uvc_light::set_uvc_lightRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uvc_light::set_uvc_lightRequest> should match
// service_traits::DataType< ::uvc_light::set_uvc_light >
template<>
struct DataType< ::uvc_light::set_uvc_lightRequest>
{
  static const char* value()
  {
    return DataType< ::uvc_light::set_uvc_light >::value();
  }
  static const char* value(const ::uvc_light::set_uvc_lightRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uvc_light::set_uvc_lightResponse> should match
// service_traits::MD5Sum< ::uvc_light::set_uvc_light >
template<>
struct MD5Sum< ::uvc_light::set_uvc_lightResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uvc_light::set_uvc_light >::value();
  }
  static const char* value(const ::uvc_light::set_uvc_lightResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uvc_light::set_uvc_lightResponse> should match
// service_traits::DataType< ::uvc_light::set_uvc_light >
template<>
struct DataType< ::uvc_light::set_uvc_lightResponse>
{
  static const char* value()
  {
    return DataType< ::uvc_light::set_uvc_light >::value();
  }
  static const char* value(const ::uvc_light::set_uvc_lightResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UVC_LIGHT_MESSAGE_SET_UVC_LIGHT_H
