// Generated by gencpp from file uvc_light/set_uvc_lightRequest.msg
// DO NOT EDIT!


#ifndef UVC_LIGHT_MESSAGE_SET_UVC_LIGHTREQUEST_H
#define UVC_LIGHT_MESSAGE_SET_UVC_LIGHTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uvc_light
{
template <class ContainerAllocator>
struct set_uvc_lightRequest_
{
  typedef set_uvc_lightRequest_<ContainerAllocator> Type;

  set_uvc_lightRequest_()
    : state(0)  {
    }
  set_uvc_lightRequest_(const ContainerAllocator& _alloc)
    : state(0)  {
  (void)_alloc;
    }



   typedef uint8_t _state_type;
  _state_type state;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(OFF)
  #undef OFF
#endif
#if defined(_WIN32) && defined(ON)
  #undef ON
#endif

  enum {
    OFF = 0u,
    ON = 1u,
  };


  typedef boost::shared_ptr< ::uvc_light::set_uvc_lightRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uvc_light::set_uvc_lightRequest_<ContainerAllocator> const> ConstPtr;

}; // struct set_uvc_lightRequest_

typedef ::uvc_light::set_uvc_lightRequest_<std::allocator<void> > set_uvc_lightRequest;

typedef boost::shared_ptr< ::uvc_light::set_uvc_lightRequest > set_uvc_lightRequestPtr;
typedef boost::shared_ptr< ::uvc_light::set_uvc_lightRequest const> set_uvc_lightRequestConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uvc_light::set_uvc_lightRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uvc_light::set_uvc_lightRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uvc_light::set_uvc_lightRequest_<ContainerAllocator1> & lhs, const ::uvc_light::set_uvc_lightRequest_<ContainerAllocator2> & rhs)
{
  return lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uvc_light::set_uvc_lightRequest_<ContainerAllocator1> & lhs, const ::uvc_light::set_uvc_lightRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uvc_light

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uvc_light::set_uvc_lightRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uvc_light::set_uvc_lightRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uvc_light::set_uvc_lightRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uvc_light::set_uvc_lightRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uvc_light::set_uvc_lightRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uvc_light::set_uvc_lightRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uvc_light::set_uvc_lightRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8f77c0161e0f2021493136bb5f3f0e51";
  }

  static const char* value(const ::uvc_light::set_uvc_lightRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8f77c0161e0f2021ULL;
  static const uint64_t static_value2 = 0x493136bb5f3f0e51ULL;
};

template<class ContainerAllocator>
struct DataType< ::uvc_light::set_uvc_lightRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uvc_light/set_uvc_lightRequest";
  }

  static const char* value(const ::uvc_light::set_uvc_lightRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uvc_light::set_uvc_lightRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 OFF=0\n"
"uint8 ON=1\n"
"uint8 state\n"
;
  }

  static const char* value(const ::uvc_light::set_uvc_lightRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uvc_light::set_uvc_lightRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct set_uvc_lightRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uvc_light::set_uvc_lightRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uvc_light::set_uvc_lightRequest_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UVC_LIGHT_MESSAGE_SET_UVC_LIGHTREQUEST_H
