// Generated by gencpp from file uvc_light/set_uvc_lightResponse.msg
// DO NOT EDIT!


#ifndef UVC_LIGHT_MESSAGE_SET_UVC_LIGHTRESPONSE_H
#define UVC_LIGHT_MESSAGE_SET_UVC_LIGHTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uvc_light
{
template <class ContainerAllocator>
struct set_uvc_lightResponse_
{
  typedef set_uvc_lightResponse_<ContainerAllocator> Type;

  set_uvc_lightResponse_()
    {
    }
  set_uvc_lightResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::uvc_light::set_uvc_lightResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uvc_light::set_uvc_lightResponse_<ContainerAllocator> const> ConstPtr;

}; // struct set_uvc_lightResponse_

typedef ::uvc_light::set_uvc_lightResponse_<std::allocator<void> > set_uvc_lightResponse;

typedef boost::shared_ptr< ::uvc_light::set_uvc_lightResponse > set_uvc_lightResponsePtr;
typedef boost::shared_ptr< ::uvc_light::set_uvc_lightResponse const> set_uvc_lightResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uvc_light::set_uvc_lightResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uvc_light::set_uvc_lightResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace uvc_light

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uvc_light::set_uvc_lightResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uvc_light::set_uvc_lightResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uvc_light::set_uvc_lightResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uvc_light::set_uvc_lightResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uvc_light::set_uvc_lightResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uvc_light::set_uvc_lightResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uvc_light::set_uvc_lightResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::uvc_light::set_uvc_lightResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::uvc_light::set_uvc_lightResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uvc_light/set_uvc_lightResponse";
  }

  static const char* value(const ::uvc_light::set_uvc_lightResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uvc_light::set_uvc_lightResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::uvc_light::set_uvc_lightResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uvc_light::set_uvc_lightResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct set_uvc_lightResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uvc_light::set_uvc_lightResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::uvc_light::set_uvc_lightResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // UVC_LIGHT_MESSAGE_SET_UVC_LIGHTRESPONSE_H
