mobile_base_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: [ "left_front", "left_back" ]
  right_wheel: [ "right_front", "right_back" ]
  publish_rate: 50
  pose_covariance_diagonal: [ 0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03 ]
  twist_covariance_diagonal: [ 0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03 ]
  cmd_vel_timeout: 0.25

  # Odometry fused with IMU is published by robot_localization, so
  # no need to publish a TF based on encoders alone.
  enable_odom_tf: false

  # Wheel separation and radius
  wheel_separation: 0.6096 # 24 in <=> 0.6096 m
  wheel_radius: 0.0762 # 3 in <=> 0.0762 m

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0
  wheel_radius_multiplier    : 1.0

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 0.15   # m/s
      min_velocity           : -0.15
      has_acceleration_limits: true
      max_acceleration       : 1.5   # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 0.5   # rad/s
      min_velocity           : -0.5
      has_acceleration_limits: true
      max_acceleration       : 5.0   # rad/s^2